##
# Copyright IBM Corporation 2017
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

# Travis CI build file
# We leverage Package-Builder

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop
    - /^issue.*$/

notifications:
  slack:
    secure: "VFUQIBCL8Kiubw7ojN3oJOs2TgobYaAZTCQePDATOMSRKRo/rDgsloGDc3kqGkLb0lAwky1lwKQjnRUsG1mEES6+W2K3QWsmzpTR1owPzZprrHrL/h1vkWdysx7ed0dBnbs8uhtD4iPe46vWZqLc1ZyfV8QxefTD9mrS4VeH7rd4qOwMgkjphaoVc0/cOkt0u8p54961HLVt4euSZf0766hfYH+1EwvoShaiK/2aKTF/hmFavB2iASHRXJnOm9S4iDWyFW2D7XEwoo9o9jOAqtYbVefGglCjUymmuNCmj1bE3NSWXJB/5KC8xFNYs7b5jZ19diu5PQK2K1HCtJvLhW2wv7cBfBFrluvz52zeHB8izYIiSV+sr6mJgnPuwaoYUObJWkLlKpTo3oPgAU/62l0KMgdn1EoBrCSDVCz5IBjLmty25nFl1oDGZITQjNIkIMUjh4dojjr+JSRDumHxje39bu8nvxsA5pxDulnWQNorvaHeWf8t2ZAqYW/ojpAlmvBr7E+U9P6DHw40FDStcI8bJGfWv8yybjMocYtTTl6FaQdfqNm3Afp5wlUxNAkAG2neRGnuitHTQ4CBHquA9NG4c7tlyafUf9UMuce3ikQiUeecNnrW2tLkKEnkO6KXwgvOCAyQrFMHncPWXfQVY/+c/2ejelCOUW8BL2pBLBY="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.2
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git
  - git clone -b master https://$GITHUB_USER:$GITHUB_PWD@github.com/IBM-Swift/Testing-Credentials.git

script:
  - ./ci/execute_script.sh

# Deploy application to Bluemix - assumes service dependencies are already bound to existing app to start successfully
deploy:
  # Deploy application to 'applications-dev' space if branch is 'develop'
  - provider: bluemixcloudfoundry
    edge: true
    username: $BLUEMIX_USER
    password: $BLUEMIX_PWD
    organization: $BLUEMIX_ORGANIZATION
    space: applications-dev
    manifest: manifest.yml               # (optional)  Defaults to manifest.yml.
    region: ng                           # (optional)  [ng, eu-gb , au-syd] Defaults to US South region (ng).
    api: https://$BLUEMIX_REGION         # (optional)  Overrides region setting if specifed for Bluemix local installations.
    on:
      branch: develop
      condition: $TRAVIS_OS_NAME = linux
  # Deploy application to 'applications-production' space if branch is 'master'
  - provider: bluemixcloudfoundry
    edge: true
    username: $BLUEMIX_USER
    password: $BLUEMIX_PWD
    organization: $BLUEMIX_ORGANIZATION
    space: applications-production
    manifest: manifest.yml               # (optional)  Defaults to manifest.yml.
    region: ng                           # (optional)  [ng, eu-gb , au-syd] Defaults to US South region (ng).
    api: https://$BLUEMIX_REGION         # (optional)  Overrides region setting if specifed for Bluemix local installations.
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
