app:
  image: ibmcom/swift-ubuntu:4.0.2
  ports:
    - "8080:8080"
  volumes:
    - .:/root/SwiftEnterpriseDemo
  command: bash -c "cd /root/SwiftEnterpriseDemo && swift package clean && swift build && ./.build/debug/SwiftEnterpriseDemo"
